name: dnn
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.8.0
  - appnope=0.1.0
  - astor=0.7.1
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - cctools=895
  - certifi=2019.6.16
  - cffi=1.12.3
  - clang=8.0.1
  - clang_osx-64=8.0.1
  - clangxx=8.0.1
  - clangxx_osx-64=8.0.1
  - compiler-rt=8.0.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - freetype=2.10.0
  - gast=0.2.2
  - gettext=0.19.8.1
  - grpcio=1.22.0
  - h5py=2.9.0
  - hdf5=1.10.5
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - keras=2.2.5
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld64=274.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.1
  - libcxxabi=8.0.1
  - libffi=3.2.1
  - libflac=1.3.1
  - libgfortran=4.0.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libogg=1.3.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.9.1
  - libsndfile=1.0.28
  - libsodium=1.0.17
  - libvorbis=1.3.5
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=8.0.1
  - mako=1.1.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.1
  - openssl=1.1.1c
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - protobuf=3.9.1
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pygpu=0.7.6
  - pyparsing=2.4.2
  - pyrsistent=0.15.4
  - pysoundfile=0.10.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pyyaml=5.1.2
  - pyzmq=18.0.2
  - readline=8.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.2.0
  - six=1.12.0
  - sqlite=3.29.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - theano=1.0.4
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.5
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.2
  - zlib=1.2.11
